---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-cyberpartner-create
  namespace: cackalacky
  labels:
    app: svc-cyberpartner-create
    broker-source: kafka
    broker-source-topic: ingress-cackalacky-cyberpartner-create
    broker-destination: kafka
    broker-destination-topic: self,cyberpartner-event-log,egress-mqtt-to-badge
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: svc-cyberpartner-create
  template:
    metadata:
      labels:
        app: svc-cyberpartner-create
        broker-source: kafka
        broker-source-topic: ingress-cackalacky-cyberpartner-create
        broker-destination: kafka
        broker-destination-topic: self,cyberpartner-event-log,egress-mqtt-to-badge
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
        - name: app-cyberpartner-create
          image: 059039070213.dkr.ecr.us-east-1.amazonaws.com/cackalacky/2025/cyberpartner/svc-cyberpartner-create
          command: ["poetry", "run", "python", "main.py", "--topic", "ingress-cackalacky-cyberpartner-create", "--group", "create-cyberpartner"]
          envFrom:
            - secretRef:
                name: doppler-ckc25-prod
      imagePullSecrets:
        - name: regcred
